### PR TITLE
Grid Docs

### PR DESCRIPTION
**Pull request by mattmanning**
To view changes pull this branch and run `jekyll serve`.

[http://localhost:4000/docs/github-integration/](http://localhost:4000/docs/github-integration/)

### CODE REVIEW

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4tiWmUji&#x2F;102-launch-burndown"> Launch Burndown</a>

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZGSpUgXj&#x2F;108-github-docs"> GitHub Docs</a>

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;J7kdBepj&#x2F;109-sharing-docs"> Sharing Docs</a>

**Comment by nzoschke** [comment]
:+1:

**Pull request merged**
