### PR TITLE
Document new SSL functionality

### PR DESCRIPTION
**Pull request by mattmanning**
screenshot 2015-10-15 18 18 59

### CODE REVIEW

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;G9kbtY9z&#x2F;107-ssl-certificates"> SSL certificates</a>

**Comment by nzoschke** [comment]
You need to deploy after changing the manifest.

**Comment by nzoschke** [comment]
And I think its `convox ssl add port crt key`

**Comment by nzoschke** [comment]
screen shot 2015-10-15 at 2 32 23 pm :facepunch:

**Comment by nzoschke** [comment]
You could also demonstrate how introspecting SSL configuratino works.

```
$ convox ssl
PORT  EXPIRES            DOMAINS     
443   9 months from now  *.foobar.com
```

**Comment by mattmanning** [comment]
@nzoschke Great suggestion. I'll add that.

**Comment by nzoschke** [comment]
:+1:

**Pull request merged**
